name: CI/CD

on: [push, pull_request]

jobs:
  linux:
    name: Linux-x86
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Configure
        working-directory: ${{github.workspace}}/server
        run: cmake -B ${{github.workspace}}/build -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET="x64-linux"
        continue-on-error: true
      - name: Print vcpkg log
        run: cat "${{github.workspace}}/server/build/vcpkg-manifest-install.log"
      - name: Build
        working-directory: ${{github.workspace}}/server
        run: cmake --build ${{github.workspace}}/server/build
