name: Compile on UNIX

on: [push, pull_request]

jobs:
  linux:
    name: Linux-x86
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: update vcpkg
        run: ${{github.workspace}}/vcpkg/vcpkg update   
        continue-on-error: true

      - name: pull vcpkg
        working-directory: ${{github.workspace}}/vcpkg
        run: git pull
        continue-on-error: true

      - name: Create BUILD folder
        working-directory: ${{github.workspace}}/server
        run: mkdir build
        continue-on-error: true
        
      - name: Configure Server
        working-directory: ${{github.workspace}}/server
        run: cmake -S . -B ${{github.workspace}}/build -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_MAKE_PROGRAM=/usr/bin/make -DCMAKE_FIND_ROOT_PATH=/usr/
        continue-on-error: true
        
      - name: Build Server
        working-directory: ${{github.workspace}}/server
        run: cmake --build ./build/
