name: compilation in unix system

# A Github Action to verify if the project can be built and executed in Windows and UNIX systems

on:
  push:
    branches: [ "main" ]
  delete:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  linux_compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: "recursive"
    
    - name: Install CMAKE
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake

    - name: Set up Vcpkg environment variables
      run: |
      export VCPKG_ROOT="$(pwd)/vcpkg"
      export CMAKE_TOOLCHAIN_FILE="$(pwd)/vcpkg/scripts/buildsystems/vcpkg.cmake"

    
    - name: launch cmake
      working-directory: ${{github.workspace}}
      run: ; cd ./server; cmake -B ./build -S .
      
    - name: build executable
      working-directory: ${{github.workspace}}/server
      run: cmake --build ./build
      
    - name: launch server
      working-directory: ${{github.workspace}}/server
      run: ./build/r-type_server
    
