name: Compile on UNIX

on: [push, pull_request]

jobs:
  linux:
    name: Linux-x86
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
          
      - name: install basics
        run: sudo apt install build-essential

      - name: Create BUILD folder
        working-directory: ${{github.workspace}}/server
        run: mkdir build
      
      - name: install NINJA
        run: python -m pip install ninja
        
      - name: set env var
        run : export CMAKE_CXX_COMPILER=/usr/bin/g++; export CMAKE_C_COMPILER=/usr/bin/gcc; export CMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake; export CMAKE_MAKE_PROGRAM=/usr/bin/make
        
      - name: Configure Server
        working-directory: ${{github.workspace}}/server
        run: cmake -S . -B ./build
        continue-on-error: true
        
      - name: delete Cache
        working-directory: ${{github.workspace}}/server/build
        run: rm -rf CMakeCache.txt
        
      - name: reload Server cache
        working-directory: ${{github.workspace}}/server
        run: cmake -S . -B ./build
        continue-on-error: true
        
      - name: Build Server
        working-directory: ${{github.workspace}}/server
        run: cmake --build ./build/
