name: Mirroring

# A Github Action to verify if the project can be built and executed in Windows and UNIX systems

on:
  push:
    branches: [ "52-test-github-actions" ]
  delete:
    branches: [ "52-test-github-actions" ]

  workflow_dispatch:

jobs:
  linux_compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install CMAKE
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake
    - name: Install CMAKE
      run: git clone https://github.com/microsoft/vcpkg.git; cd vcpkg; ./bootstrap-vcpkg.sh; export CMAKE_TOOLCHAIN_FILE="$(pwd)/vcpkg/scripts/buildsystems/vcpkg.cmake"
    - name: launch cmake
      working-directory: ${{github.workspace}}/server
      run: cmake -B ./build -S .
    - name: build executable
      working-directory: ${{github.workspace}}/server
      run: cmake --build ./build
    - name: launch server
      working-directory: ${{github.workspace}}/server
      run: ./build/r-type_server
    
